# This file provides instructions for packaging.

`Alien-Wenity`
	perl_version_from m`Alien::Wenity`;
	version_from      m`Alien::Wenity`;
	readme_from       m`Alien::Wenity`;
	test_requires     p`Test::More 0.61`;
	test_requires     p`IO::Prompt::Tiny`;
	requires          p`File::ShareDir`;
.

